services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /var/www/html/frontend
    command: sh -c "rm -rf .next && npm install && npm run dev"
    volumes:
      - ./frontend:/var/www/html/frontend
      - /var/www/html/frontend/node_modules
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: /api
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
      NEXT_TELEMETRY_DISABLED: 1
      TURBOPACK_WATCHING: true